=== AlvaroFernandezEdMadrid/LMXML/dos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT factura (datos_emisor, datos_cliente, datos_detalle)>
<!ATTLIST factura numero ID #REQUIRED>
<!ATTLIST factura fecha CDATA #REQUIRED>
<!ATTLIST factura importe_total CDATA #REQUIRED>
<!ELEMENT  datos_emisor (nombre, cif, telefono)>
<!ELEMENT datos_cliente (nombre, cif, telefono)>
<!ELEMENT datos_detalle (linea+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT linea (descripcion, cantidad, oferta?, pvp)>
<!ATTLIST linea codigo_art ID #REQUIRED> 
<!ATTLIST linea tipo (Libro|DVD|Varios) #IMPLIED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta (#EMPTY)>
<!ELEMENT pvp (#PCDATA)>

=== AlvaroFernandezEdMadrid/LMXML/EjDTD/2/dos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "dos.dtd">
<factura numero="A1" fecha="2002-02-12" importe_total="85">
    <datos_emisor>
        <nombre>Libreria Coslada</nombre>
        <cif>12345678B</cif>
        <telefono>666000000</telefono>
    </datos_emisor>
    <datos_cliente>
        <nombre>IES Luis Braille</nombre>
        <cif>87654321A</cif>
        <telefono>606606606</telefono>
    </datos_cliente>
    <datos_detalle>
        <linea codigo_art="AW7" tipo="Libro">
            <descripcion>Aplicaciones Web</descripcion>
            <cantidad>2</cantidad>
            <oferta />
            <pvp>25</pvp>
        </linea>
        <linea codigo_art="LM5">
            <descripcion>Lenguaje de Marcas</descripcion>
            <cantidad>1</cantidad>
            <pvp>30</pvp>
        </linea>
    </datos_detalle>
</factura>
