=== AlvaroFernandezEdMadrid/LMXML/uno.dtd
<!ELEMENT aeropuerto (nombre, vuelo*, fecha)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT vuelo (diario?, origen, destino, horaSalida, horaLlegada)>
 <!ATTLIST vuelo codigo ID #REQUIRED>
 <!ATTLIST vuelo estado (C|E|R) "E">
 <!ELEMENT fecha (#PCDATA)>
 <!ELEMENT diario EMPTY>
 <!ELEMENT origen (#PCDATA)>
 <!ELEMENT destino (#PCDATA)>
 <!ELEMENT horaSalida (#PCDATA)>
<!ELEMENT horaLlegada (#PCDATA)>

=== AlvaroFernandezEdMadrid/LMXML/uno.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto SYSTEM "uno.dtd">
<aeropuerto>
  <nombre>JFK</nombre>
  <vuelo codigo ="V22" estado ="C">
  <diario  />
  <origen>New York</origen>
  <destino>Chicago</destino>
  <horaSalida>9:30</horaSalida>
  <horaLlegada>11:30</horaLlegada>
  </vuelo>
<fecha>13 Marzo</fecha>
</aeropuerto>
