=== AlvaroFernandezEdMadrid/LMXML/EjDTD/7/siete.dtd
<!ELEMENT boletines (modulo*)>
<!ELEMENT modulo (alumno*)>
<!ATTLIST modulo nombre CDATA #REQUIRED>
<!ELEMENT alumno (nombre, boletin)>
<!ATTLIST alumno matricula ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT boletin (nota*)>
<!ELEMENT nota (#PCDATA)>
<!ATTLIST nota tipo (TEORIA|PRACTICA) #IMPLIED>

=== AlvaroFernandezEdMadrid/LMXML/EjDTD/7/siete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boletines SYSTEM "siete.dtd">
<boletines>
    <modulo nombre="SSOO">
        <alumno matricula="X501">
            <nombre>Darío Bueno Gutiérrez</nombre>
            <boletin>
                <nota tipo="TEORIA">5</nota>
                <nota tipo="PRACTICA">4,5</nota>
            </boletin>
        </alumno>
        <alumno matricula="X502">
            <nombre>Rodrigo Vaquero Gutiérrez</nombre>
            <boletin>
                <nota tipo="TEORIA">9</nota>
                <nota tipo="PRACTICA">7</nota>
            </boletin>
        </alumno>
        <alumno matricula="X503">
            <nombre>Inés Bueno Gutiérrez</nombre>
            <boletin>
                <nota tipo="TEORIA">8</nota>
                <nota tipo="PRACTICA">9</nota>
            </boletin>
        </alumno>
        <alumno matricula="X504">
            <nombre>Violeta Duro Gutiérrez</nombre>
            <boletin>
                <nota tipo="TEORIA">4,5</nota>
                <nota tipo="PRACTICA">7</nota>
            </boletin>
        </alumno>
    </modulo> 
</boletines>
