=== AlvaroFernandezEdMadrid/LMXML/xsd/ejercicios2/cuatro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="apellido">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z\s]{1,30})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nombre">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z\s]{1,20})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="identificador">
        <xs:restriction base="xs:string">
            <xs:pattern value="(U|E){1}\d{1,5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-z]{1,15}[@][a-z]{1,25}[.][a-z]{2,4})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="conexion">
        <xs:attributeGroup ref="atribConex" />
    </xs:complexType>

    <xs:attributeGroup name="atribConex">
        <xs:attribute name="fecha" type="xs:date" use="required" />
        <xs:attribute name="hora" type="xs:time" use="required" />
        <xs:attribute name="tiempo" type="xs:positiveInteger" use="required" />
    </xs:attributeGroup>

    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="nombre" type="nombre"></xs:element>
            <xs:element name="apellido1" type="apellido"></xs:element>
            <xs:element name="apellido2" type="apellido"></xs:element>
            <xs:element name="email" type="email"></xs:element>
            <xs:element name="conexiones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="conexion" type="conexion" minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="identificador" />
    </xs:complexType>

    <xs:complexType name="tipoPersonaAmpliado">
        <xs:complexContent>
            <xs:extension base="tipoPersona">
                <xs:sequence>
                    <xs:element name="departamento">
                        <xs:complexType>
                            <xs:choice>
                                <xs:element name="marketing" />
                                <xs:element name="administracion" />
                                <xs:element name="informatica" />
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="registro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" type="tipoPersona" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" type="tipoPersonaAmpliado"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlvaroFernandezEdMadrid/LMXML/xsd/ejercicios2/cuatro.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cuatro.xsd">
    <usuarios>
        <usuario id="U123">
            <nombre>Ana</nombre>
            <apellido1>Sanz</apellido1>
            <apellido2>Tapia</apellido2>
            <email>asanz@jmail.com</email>
            <conexiones>
                <conexion fecha="2014-02-23" hora="19:15:40" tiempo="122" />
                <conexion fecha="2014-02-23" hora="20:30:22" tiempo="617" />
                <conexion fecha="2014-02-24" hora="11:18:31" tiempo="25" />
            </conexiones>
        </usuario>
        <usuario id="U96">
            <nombre>Pedro</nombre>
            <apellido1>Ruiz</apellido1>
            <apellido2>Hierro</apellido2>
            <email>pruiz@jotmail.com</email>
            <conexiones>
                <conexion fecha="2014-02-25" hora="20:33:55" tiempo="390" />
            </conexiones>
        </usuario>
    </usuarios>
    <empleados>
        <empleado id="E4">
            <nombre>Marta</nombre>
            <apellido1>Vera</apellido1>
            <apellido2>Gil</apellido2>
            <email>mvera@yajooo.es</email>
            <conexiones>
            </conexiones>
            <departamento>
                <marketing/>
            </departamento>
        </empleado>
    </empleados>
</registro>
