=== AlvaroFernandezEdMadrid/LMXML/EjDTD/4/cuatro.dtd
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (nombre_trabajador, fecha, plazo_revision, sucursal, articulos)>
<!ATTLIST pedido codigo ID #REQUIRED>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ATTLIST pedido observ (urgente|incompleto) #IMPLIED>
<!ELEMENT plazo_revision (#PCDATA)>
<!ELEMENT sucursal (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (unidades, precio_ud, observaciones)>
<!ATTLIST articulo codigo ID #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio_ud (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>

=== AlvaroFernandezEdMadrid/LMXML/EjDTD/4/cuatro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "cuatro.dtd">
<pedidos>
    <pedido codigo="P1" observ="incompleto">
        <nombre_trabajador>Juan Pérez</nombre_trabajador>
        <fecha>2024-04-11</fecha>
        <plazo_revision>2024-04-15</plazo_revision>
        <sucursal>
            <nombre>Sucursal Barcelona</nombre>
            <direccion>173 Calle Cebolla</direccion>
        </sucursal>
        <articulos>
            <articulo codigo="A1">
                <unidades>2</unidades>
                <precio_ud>10.00</precio_ud>
                <observaciones>Voluminoso</observaciones>
            </articulo>
            <articulo codigo="A2">
                <unidades>1</unidades>
                <precio_ud>20.00</precio_ud>
                <observaciones>Pequenio desperfecto</observaciones>
            </articulo>
        </articulos>
    </pedido>
    <pedido codigo="P2" observ="urgente">
        <nombre_trabajador>Maria López</nombre_trabajador>
        <fecha>2024-04-12</fecha>
        <plazo_revision>2024-04-18</plazo_revision>
        <sucursal>
            <nombre>Sucursal Sevilla</nombre>
            <direccion>789 Avenida Flamenco</direccion>
        </sucursal>
        <articulos>
            <articulo codigo="A3">
                <unidades>3</unidades>
                <precio_ud>15.00</precio_ud>
                <observaciones>Abolladura en la caja</observaciones>
            </articulo>
        </articulos>
    </pedido>
</pedidos>
