=== AlvaroFernandezEdMadrid/LMXML/EjDTD/3/tres3.dtd
<!ELEMENT liga (partido+)>
<!ELEMENT partido (equipos+)>
<!ELEMENT equipos (local, visitante)>
<!ELEMENT local EMPTY>
<!ELEMENT visitante EMPTY>
<!ATTLIST local nombre CDATA #REQUIRED>
<!ATTLIST visitante nombre CDATA #REQUIRED>
<!ATTLIST local goles CDATA #REQUIRED>
<!ATTLIST visitante goles CDATA #REQUIRED>

=== AlvaroFernandezEdMadrid/LMXML/EjDTD/3/tres3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "tres3.dtd">
<liga>
    <partido>
        <equipos>
            <local nombre="Nottingham Presa" goles="0" />
            <visitante nombre="Inter de Mitente" goles="1" />
        </equipos>
    </partido>
    <partido>
        <equipos>
            <local nombre="Vodka Juniors" goles="3" />
            <visitante nombre="Sparta da Risa" goles="3" />
        </equipos>
    </partido>
    <partido>
        <equipos>
            <local nombre="Water de MÃºnich" goles="3" />
            <visitante nombre="Esteaua es del grifo" goles="2" />
        </equipos>
    </partido>
</liga>
