=== AlvaroFernandezEdMadrid/LMXML/EjDTD/3/tres1.dtd
<!ELEMENT liga (partido+)>
<!ELEMENT partido (equipos+)>
<!ELEMENT equipos (local, visitante)>
<!ELEMENT local (nombre, goles)>
<!ELEMENT visitante (nombre, goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>

=== AlvaroFernandezEdMadrid/LMXML/EjDTD/3/tres1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "tres1.dtd">
<liga>
    <partido>
        <equipos>
            <local>
                <nombre>Nottingham Presa</nombre>
                <goles>0</goles>
            </local>
            <visitante>
                <nombre>Inter de Mitente</nombre>
                <goles>1</goles>
            </visitante>
        </equipos>
    </partido>
    <partido>
        <equipos>
            <local>
                <nombre>Vodka Juniors</nombre>
                <goles>3</goles>
            </local>
            <visitante>
                <nombre>Sparta da Risa</nombre>
                <goles>3</goles>
            </visitante>
        </equipos>
    </partido>
    <partido>
        <equipos>
            <local>
                <nombre>Water de MÃºnich</nombre>
                <goles>3</goles>
            </local>
            <visitante>
                <nombre>Esteaua es del grifo</nombre>
                <goles>2</goles>
            </visitante>
        </equipos>
    </partido>
</liga>
